//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetAngular.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class assetMVCEFDBEntities7 : DbContext
    {
        public assetMVCEFDBEntities7()
            : base("name=assetMVCEFDBEntities7")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<asset_def> asset_def { get; set; }
        public virtual DbSet<asset_master> asset_master { get; set; }
        public virtual DbSet<asset_type> asset_type { get; set; }
        public virtual DbSet<logintbl> logintbls { get; set; }
        public virtual DbSet<purchase_order> purchase_order { get; set; }
        public virtual DbSet<userReg> userRegs { get; set; }
        public virtual DbSet<vendor_creation> vendor_creation { get; set; }
    }
}
