//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetAngular.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class logintbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public logintbl()
        {
            this.userRegs = new HashSet<userReg>();
        }
    
        public int l_id { get; set; }
        public string uname { get; set; }
        public string pass { get; set; }
        public string utype { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<userReg> userRegs { get; set; }
    }
}
