//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetAngular.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vendor_creation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public vendor_creation()
        {
            this.asset_master = new HashSet<asset_master>();
            this.purchase_order = new HashSet<purchase_order>();
        }
    
        public decimal vd_id { get; set; }
        public string vd_name { get; set; }
        public string vd_type { get; set; }
        public Nullable<decimal> vd_atype_id { get; set; }
        public DateTime vd_from { get; set; }
        public string vd_fromstr
        {
            get
            {
                return vd_from.ToString("yyyy/MM/dd");
            }
        }
        public DateTime vd_to { get; set; }
        public string vd_tostr
        {
            get
            {
                return vd_to.ToString("yyyy/MM/dd");
            }
        }
        public string vd_addr { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<asset_master> asset_master { get; set; }
        public virtual asset_type asset_type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<purchase_order> purchase_order { get; set; }
    }
}
